### ISSUE TITLE
Setup hangs after creating files

### ISSUE THREAD

**Issue by shtrom** [asamuzaK/withExEditor#109]
The setup hangs after having created (or updated) the files

```
withExEditorHost$ npm install --production && node ./index.js setup "--overwrite-config" "--browser=firefox" "--editor-path" "/usr/local/bin/gvim" "--overwrite-editor-config" "--editor-args" ""
npm notice created a lockfile as package-lock.json. You should commit this file.
added 38 packages from 21 contributors and audited 4138 packages in 20.394s
found 1 moderate severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
(node:69975) ExperimentalWarning: The fs.promises API is experimental
Created: /Users/omehani/Library/Application Support/withexeditorhost/config/firefox
Created: /Users/omehani/Library/Application Support/withexeditorhost/config/firefox/withexeditorhost.sh
Created: /Users/omehani/Library/Application Support/Mozilla/NativeMessagingHosts/withexeditorhost.json
Created: /Users/omehani/Library/Application Support/withexeditorhost/config/firefox/editorconfig.json
```

It hangs forever after this.

I'm not sure how to debug it further, but happy for follow-up instructions.

**Comment by asamuzaK** [comment]
Which host do you use?
* binary
* npm
* source code

**Comment by shtrom** [comment]
A straight git clone.

**Comment by asamuzaK** [comment]
I can't reproduce it on Windows 10.

Add `console.log(code);` at [main.js#L637](https://github.com/asamuzaK/withExEditorHost/blob/master/modules/main.js#L637) (between `const handleExit = code => {` and `if (isDir(TMPDIR_APP)) {` line) and check if `exit` event is fired?

It should log `0`.

If number other than `0` is logged:
* Check exit code [Process | Node.js v11.12.0 Documentation](https://nodejs.org/api/process.html#process_exit_codes)

If there isn't any log at all:
* Something wrong with Node.js?

**Comment by shtrom** [comment]
Nothing printed. Somehow that never seems to exit. This is under both Linux and OS X.

```
[21:17:16] ~/bordel/default-env/vendor/withExEditorHost$ git -P diff
diff --git a/modules/main.js b/modules/main.js
index 10770d5..a50c2d6 100644
--- a/modules/main.js
+++ b/modules/main.js
@@ -634,6 +634,7 @@ const readStdin = chunk => {
  * @returns {void}
  */
 const handleExit = code => {
+    console.log(code);
   if (isDir(TMPDIR_APP)) {
     removeDir(TMPDIR_APP, TMPDIR);
   }
[21:17:55] ~/bordel/default-env/vendor/withExEditorHost$ node --version
v11.12.0
[21:17:20] ~/bordel/default-env/vendor/withExEditorHost$ npm -v
6.9.0
[21:17:22] ~/bordel/default-env/vendor/withExEditorHost$ npm run setup -- --overwrite-config --browser=firefox --editor-path $(which gvim) --overwrite-editor-config --editor-args ""


> withexeditorhost@5.0.0 setup /home/shtrom/bordel/default-env/vendor/withExEditorHost
> npm install --production && node ./index.js setup "--overwrite-config" "--browser=firefox" "--editor-path" "/usr/bin/gvim" "--overwrite-editor-config" "--editor-args" ""

audited 4135 packages in 3.945s
found 1 moderate severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
(node:12356) ExperimentalWarning: The fs.promises API is experimental
Created: /home/shtrom/.config/withexeditorhost/config/firefox
Created: /home/shtrom/.config/withexeditorhost/config/firefox/withexeditorhost.sh
Created: /home/shtrom/.mozilla/native-messaging-hosts/withexeditorhost.json
Created: /home/shtrom/.config/withexeditorhost/config/firefox/editorconfig.json
^C
```

**Comment by shtrom** [comment]
Ok, this seems to be due to the `process.stdin.on("data", readStdin);` in index.js. It expects some data to be input; if I give it a  `^D` it terminates, and the status code is output.

Note that I'm specifying all parameters on the command line, so no input should be expected here.

**Comment by shtrom** [comment]
Actually, everything still seems to work if I comment out https://github.com/asamuzaK/withExEditorHost/blob/master/index.js#L39; even without passing any argument on the command line.

**Comment by asamuzaK** [comment]
Filed [Setup hangs after creating files · Issue #55 · asamuzaK/withExEditorHost](https://github.com/asamuzaK/withExEditorHost/issues/55)

**Comment by shtrom** [comment]
Damn, you were faster than me :stuck_out_tongue_winking_eye: 

I was wondering why I couldn't create a PR https://github.com/asamuzaK/withExEditor/compare/master...shtrom:ignore-stdin?expand=1

**Comment by shtrom** [comment]
Yeah, that fixed it for me :ok_hand:
