### ISSUE TITLE
Environment culling causes all editors to fail to start

### ISSUE THREAD

**Issue by Celti** [asamuzaK/withExEditor#11]
On Linux, withExEditor _only_ passes `$DISPLAY` to the editor's environment. This causes many editors, and _all_ editors when a display manager has set `$XAUTHORITY`, to fail to to launch with often confusing errors.

At the barest minimum, all of `$USER`, `$HOME`, `$DISPLAY`, `$XAUTHORITY`, `$LANG`, and `$PATH` should be passed to the new editor, but many, _many_ others may be necessary depending on the exact software in use (Qt5-based editors may require `$QT_QPA_PLATFORMTHEME`, while any number of editor plugins may require supplementary environment for configuration, normally configured in a user's login scripts).

Is there a reason the environment is so sharply restricted, instead of passing most or all variables through so that the editor knows the environment it is using?

**Comment by Celti** [comment]
Aaah, as I look into the SDK to see about fixing this myself I see `system/child_process` requires/does the environment culling itself.

I'm not terribly familiar with this; would it be possible to just pass `system.env` in to populate the `env` object for `ChildProcess`?

**Comment by asamuzaK** [comment]
> would it be possible to just pass system.env in to populate the env object for ChildProcess?

That looks reasonable.
Please wait for the next development release?
Thanks.

**Comment by Celti** [comment]
Will do — many thanks!

**Comment by asamuzaK** [comment]
Bad news
Can't enumerate environment variable.
It needs to be passed one by one.
$USER, $HOME, $DISPLAY, $XAUTHORITY, $LANG, $PATH, and what else should it be passed?

**Comment by Celti** [comment]
I've confirmed on my local machine that those six are enough for most functionality for every editor I have installed, as well as for several terminal emulators (for TUI-based text editors). Anything else _should_ be doable using editor-specific configuration (though less convenient for it).

Thanks for the quick turnaround on this!

**Comment by asamuzaK** [comment]
Released v1.7.0-a7 [withExEditor :: Versions :: Add-ons for Firefox](https://addons.mozilla.org/en-US/firefox/addon/withexeditor/versions/)
Please try.

**Comment by Celti** [comment]
That works flawlessly — and 100% e10s-friendly, unlike any other extension of the sort out there right now. Many thanks for your work.

**Comment by asamuzaK** [comment]
Maybe Development Channel won't automatically update even when 1.7.0 Release Version is released.
I'll post a comment here when 1.7.0 is released, so please update manually.

**Comment by asamuzaK** [comment]
Forgot to say,

> At the barest minimum, all of $USER, $HOME, $DISPLAY, $XAUTHORITY, $LANG, and $PATH should be passed to the new editor

That was a big help, thanks a lot.

**Comment by Celti** [comment]
> That was a big help, thanks a lot.

No worries! It wouldn't be much of a bug report if I didn't even _try_ and figure out how to fix it! ;)

Speaking of, I was discussing the problem in #jetpack on irc.mozilla.org, and it was suggested that “you could use js-ctypes to do the necessary libc calls”. While the current solution works for the majority of cases, that'd be a good starting point for an alternative.

**Comment by asamuzaK** [comment]
`js-ctypes.jsm` needs to be used with `require("chrome")` which will be deprecated.

Thanks anyway.

**Comment by asamuzaK** [comment]
Released v1.7.0 [withExEditor :: Add-ons for Firefox](https://addons.mozilla.org/ja/firefox/addon/withexeditor/)
