### ISSUE TITLE
Keyboard macro / Key mapping

### ISSUE THREAD

**Issue by hraP93SZrh** [asamuzaK/withExEditor#114]
Not so long ago (v.4.2.6), there was something called an "access-key" which when invoked opened the editor with the contents to be edited -- CTRL + Shift + <access-key>

Now (v.6.0.1), this no longer seems to be the case.  

Is there a way to invoke withExEditor from a keyboard combination?  Or, is the context menu the only way to access the Add-on?

Thank you.

**Comment by asamuzaK** [comment]
You can set them from add-on management page.

* Open "about:addons" (Ctrl + Shift + A)
* Click tools menu (gear icon on the upper right)
* Select "Manage Extension Shortcuts"

**Comment by hraP93SZrh** [comment]
So it is.  Thank you very much asamuzaK.  

Don't know if I ever would have found that.
