### ISSUE TITLE
No response on clicking “Edit text with nvim” 

### ISSUE THREAD

**Issue by icyphox** [asamuzaK/withExEditor#117]
I’m trying to set this up to work with Neovim, I believe I’ve configured it correctly. But when I do a right-click → Edit text with nvim, nothing happens. Any logs/configs that I can provide to help you, help me?

**Comment by asamuzaK** [comment]
More info please

* OS?
* Which browser?
* Host: binary or npm?
* Open options page:
  * Is host connected?
  * Is host version compatible?

**Comment by icyphox** [comment]
Sure. 

- Linux (elementaryOS Juno)
- Firefox 67.0
- Host installed via npm
- Yes the host is both connected, and shows as compatible

**Comment by asamuzaK** [comment]
Take a look at `~/.config/withexeditorhost/config/firefox/editorconfig.json`
Is "editorPath" correct?

**Comment by icyphox** [comment]
```json
{
  "editorPath": "/usr/bin/nvim",
  "cmdArgs": [
    "/tmp/firefox_edit.txt"
  ]
}
```

Looks good to me. I've tried without `cmdArgs` too, no difference.

**Comment by asamuzaK** [comment]
* Open browser console (Ctrl + Shift + J)
* Open options page
  * Add check to `Notify Host Error`
  * Reload withExEditor
* Right click on textarea and choose `Edit text with nvim`

Any errors notified and/or logged in browser console?

**Comment by icyphox** [comment]
Absolutely nothing. For what it's worth, my terminal is `gnome-terminal`. Any issues with that? I recall reading about another similar extension having issues with `gnome-terminal`.

**Comment by asamuzaK** [comment]
> Any issues with that?

Never heard of.
Can you give me the link to that issue?

**Comment by asamuzaK** [comment]
What happens if you change the editor for example `gedit`
```
{
  "editorPath": "/usr/bin/gedit",
  "cmdArgs": []
}
```

**Comment by icyphox** [comment]
> Can you give me the link to that issue?

Right, so it wasn't an issue after all. This project: https://github.com/jlebon/textern#notes-on-gnome-terminal

The note on `gnome-terminal` is what you're looking for.

**Comment by icyphox** [comment]
Yes looks like `gedit` works.

**Comment by asamuzaK** [comment]
How about this?

```
{
  "editorPath": "/path/to/gnome-terminal",
  "cmdArgs": [
    "--wait",
    "--",
    "nvim"
  ]
}
```

**Comment by icyphox** [comment]
Nice! That did the trick. Thanks a bunch :)
