### ISSUE TITLE
Host version: Incompatible

### ISSUE THREAD

**Issue by inkarkat** [asamuzaK/withExEditor#118]
### Problem

I've just installed the Firefox add-on (version 6.0.3) from the Mozilla site and the host (version 5.1.4) via `npm install -g`.

I then get _Host Connection: Connected_, but _Host Version: Incompatible_, and nothing happens. Couldn't find any existing issues about that.

My system is Ubuntu 16.04 LTS 64-bit with NodeJS v12.7.0, npm 6.10.0, Firefox 68.0.1. Also tried integrating with Chromium 74.0.3729.169, same problem. I also tried this on another (similar) Ubuntu + Firefox, with the same problem.

When I run the host manually, it prints out a JSON message and blocks; no crashes:

```
$ ~/.config/withexeditorhost/config/firefox/withexeditorhost.sh
C{"withexeditorhost":{"message":"getEditorConfig","status":"ready"}}^C
```

In the Browser Console, I see the following error on enabling the plugin:

```
Could not establish connection. Receiving end does not exist. 7 content.js:88:15
    logErr moz-extension://8fee7dba-8552-49b1-9368-e09376529f44/js/content.js:88
    handleDisconnectedPort moz-extension://8fee7dba-8552-49b1-9368-e09376529f44/js/content.js:1777
    handleConnectedPort moz-extension://8fee7dba-8552-49b1-9368-e09376529f44/js/content.js:1791
```

### enhancement request

The _details_ on the Options page just say _If "Unknown" or "Incompatible", update the host._ I think more details should be given there (like _expected {"version": "6.0"} or greater but was {"version: "5.1.4"})_. As I've just installed everything freshly and seem to have latest versions, the error currently doesn't make sense to me.

### ideas?
Also, if you have an idea how to fix my issue, or if you need additional information, I'd highly appreciate this. I've also tried out the [Textern](https://github.com/jlebon/textern) add-on, but yours looks more accomplished, and I also need support for editable elements other than simple textareas, which Textern doesn't have yet.

**Comment by asamuzaK** [comment]
Looks like a dependency issue.

What happens if you install prev version of withExEditorHost?

```
npm i -g withexeditorhost@5.1.3
```

After that, restart your browser.

**Comment by inkarkat** [comment]
No, that doesn't help. I tried 5.1.3 and 5.1.0; same problem, after restarting the browser or disabling / enabling the add-on. As I said, I can manually start `withexeditorhost.sh` just fine, there's no error message, stack trace, just some JSON output that looks normal.

What kind of messaging is happening between add-on and host? My browsers are using an HTTP proxy to access the Internet; could that interfere with the (local) connection to the host (e.g. by mangling / suppressing the payload)?

**Comment by inkarkat** [comment]
I'm now at home (where I have direct Internet access, and turn off the proxy (through the FoxyProxy Firefox add-on)). Re-enabled _withExEditor_, and it immediately established the connection and said _Compatible_! (I'm actually typing this in gedit through your add-on.)

So, it looks like my previous hunch was right and the configured Internet proxy is to blame (I use an automatic proxy configuration URL, at least in this browser). I think the proxy will be bypassed for `localhost` URLs (but then your add-on should work, right?), but I don't know much about the proxy configuration, nor how the Firefox API handles these. Hope you have a clue based on my finding. I can report back additional information on Monday, when I'm back in the office.

**Comment by asamuzaK** [comment]
Set npm like below?

```
npm config set proxy "http://<proxyserver>:<port>/" -g
npm config set https-proxy "https://<proxyserver>:<port>/" -g
npm install -g withexeditorhost
```

Refs
[npm-config](https://docs.npmjs.com/cli/config)
[npm-config (misc)](https://docs.npmjs.com/misc/config)

**Comment by asamuzaK** [comment]
Forget about the previous comment, that was workaround when npm install fails.

**Comment by asamuzaK** [comment]
Try build.
[v6.0.4a1](https://github.com/asamuzaK/withExEditor/tree/compat/dest)

Check if it works under proxy server.

**Comment by inkarkat** [comment]
Alright, thank you for your efforts! I'll report back on Monday (when I'm back in the office that has the mandatory proxy).

**Comment by asamuzaK** [comment]
Updated try build.
Added console.log that outputs host message.
Open browser console (Ctrl + Shift + J) and please tell me the message.
It should be something like
```
hostVersion: Object { isLatest: true, latest: "5.1.4", result: 1 }
```

Thanks

**Comment by inkarkat** [comment]
The problem persists with version 6.0.4a2, nothing is logged to the browser console (when enabling the add-on). I've verified this with a clean Firefox profile, and checked that the alpha build has been installed.

Also, I'm not so sure about the proxy any longer. If I completely disable it (_Direct connection to the Internet_), the add-on should work (like it did at home on the weekend), even though I could then only access Intranet pages, right? But in the office, it doesn't work at all, regardless of the proxy settings. That suggests to me that it's not that the add-on is mistakenly trying to contact the host process through the proxy (and getting a garbled response). Rather, it looks like the add-on is requiring Internet access (but what for?), and fails to use the proxy that is configured.

Apart from the proxy, there are no other mandatory corporate settings (like firewalls or blocked hosts) that I'm aware of; I'm the sole administrator of my systems.

**Comment by asamuzaK** [comment]
Add-on and host use stdin and stdout to exchange messages, so the proxy settings should not affect exchanging messages, IMO.

You say that there is no log left from the host, there may be some problem within the host.

Could you check the setting of npm?
````
npm config ls -l
````

What are the `proxy` and `https-proxy` values?

**Comment by inkarkat** [comment]
`proxy` and `https-proxy` point to the corporate proxy URL; I needed that to download the host and its dependencies. Are the `npm` config settings really still used for running the node executable after it's been downloaded? As I showed above, the host can be invoked manually without crashing (in both proxy and non-proxy environments).

I just unplugged the corporate LAN, and connected to the office's guest WLAN instead (that doesn't require a proxy). After restarting the browser, the add-on starts working again. Then I switched back to LAN. The add-on's icon does not recognize the change and still signals okay, but triggering an "Edit Text with" doesn't bring up the editor any longer. This is with the same host process (that during WLAN worked fine) still running. After pressing |Reload withExEditor| in the add-on settings, I get the _Incompatible_ again and also the icon changes to the red exclamation mark.

So the network connection (and as far as I know the only difference between WLAN and LAN is the mandatory proxy for the latter) does have an effect on the add-on <-> host connection, even immediately, to a running browser and host. It surprises me that the communication is via stdin/stdout; something in there still has to involve the network. The error console shows

```
Error: Could not establish connection. Receiving end does not exist. 3 content.js:1765:20
```

That's `requestPortConnection()` in the add-on source - sounds like network socket, doesn't it?

**Comment by asamuzaK** [comment]
The function which checks version compatibility in the host also checks for the latest version.
And the latest version is checked by the package-json module.
If there is a possibility of something affected by the proxy, I think it is the package-json module.
I have not checked the source of the package-json module properly, but it seems to use the http client.

I'll add a try version of the host later, please wait for a while.

**Comment by asamuzaK** [comment]
PS:
The content.js error is a known bug.
It happens, for example, when you restart the add-on after launching the browser.
There's a workaround, but it's not compatible with Chrome, so I'm leaving it as it is.

**Comment by asamuzaK** [comment]
I've uploaded host for a try.
```
npm i -g withexeditorhost@dev
```

**Comment by inkarkat** [comment]
It's working now! Great job! Updating to `withexeditorhost@5.1.5-a.1` made it work directly after starting Firefox again. I now also see the `{hostVersion: {isLatest: null, latest: null, result: 1}}` that you've added, in the browser console.

Whew, that was quite some troubleshooting. Thank you very much!

**Comment by asamuzaK** [comment]
Filed [Host version check on proxy server #64](https://github.com/asamuzaK/withExEditorHost/issues/64).
Let's fix the host side.
