### ISSUE TITLE
Text file name as placeholder

### ISSUE THREAD

**Issue by mb720** [asamuzaK/withExEditor#122]
Hi and thanks a lot for withExEditor!

I'm trying to use nvim for writing text into Firefox. My terminal is termite.

My current version of `editorconfig.json` is this:

    {
      "editorPath": "/usr/bin/termite",
      "cmdArgs": ["--exec=nvim"],
      "fileAfterCmdArgs": true
    }

I can see that withExEditor will issue a command like this

>/usr/bin/termite --exec=nvim /tmp/withExEditor/1822667/tmpFiles/1/139/github.com/new_comment_field.txt

Unfortunately that doesn't work since the part after `-exec=` needs to be quoted if there are is a command (`nvim` in our case) with parameters.

This would work:

>/usr/bin/termite --exec="nvim /tmp/withExEditor/1822667/tmpFiles/1/139/github.com/new_comment_field.txt"

Is there a way to specify this in`editorconfig.json`? Maybe using a placeholder for the edited file:

    {
      "editorPath": "/usr/bin/termite",
      "cmdArgs": ["--exec=\"nvim {FILE_PLACEHOLDER}\""],
    }

**Comment by asamuzaK** [comment]
What happens if you specify `cmdArgs` like this?

```
{
  "editorPath": "/usr/bin/termite",
  "cmdArgs": ["-e", "nvim"]
}
```

or

```
{
  "editorPath": "/usr/bin/termite",
  "cmdArgs": ["-e", "nvim", "--"]
}
```

**Comment by mb720** [comment]
The commands become

>/usr/bin/termite -e nvim /tmp/withExEditor/1896339/tmpFiles/1/162/github.com/new_comment_field.txt

and

>/usr/bin/termite -e nvim -- /tmp/withExEditor/1889445/tmpFiles/1/1/en.wikipedia.org/searchInput.txt

respectively. It doesn't work since the file name isn't passed to nvim, instead it opens a `[No Name]` buffer.

[Here's](https://github.com/thestinger/termite/issues/308) a discussion about the command argument issue in termite.

**Comment by asamuzaK** [comment]
Okay, it's a host issue, so re-filed in withExEditorHost.
Please follow [Add support for placeholder in command arguments #71](https://github.com/asamuzaK/withExEditorHost/issues/71).

**Comment by asamuzaK** [comment]
Can you try just one more?
I think it will either fail or throw an error, but I want to make sure just in case.

```
{
  "editorPath": "/usr/bin/termite",
  "cmdArgs": ["--exec=\"nvim $2\""]
}
```

**Comment by mb720** [comment]
Hmm, it doesn't seem to do anything. Firefox' console doesn't log an error.
I use withExEditor 5.2.1, by the way.
