### ISSUE TITLE
Failed to parse SourceMap message on chrome devtool

### ISSUE THREAD

**Issue by shaoran** [asamuzaK/withExEditor#126]
I've started using this really nice extension in Google chrome. I am a web developer so I work a lot with an open devtools of chrome. Since I installed this extension I get this warning all the time:

> DevTools failed to parse SourceMap: chrome-extension://koghhpkkcndhhclklnnnhcpkkplfkgoi/lib/browser-polyfill.min.js.map

I know it's not a big deal but after a while I feel like it's spaming the devtools. It would be nice to remove the map file from the production build.

**Comment by asamuzaK** [comment]
* Open Developer tools (Ctrl + Shift + I)
* Open Settings (F1)
* In Prefences, uncheck `Enable JavaScript source maps`

**Comment by shaoran** [comment]
Thanks for the reply, but like I said, I work a lot with a the dev tools and I cannot disable that otherwise I cannot use the source maps from my own projects.

**Comment by asamuzaK** [comment]
I can confirm that error in Brave which uses Chrome 80 with developer mode enabled, <del>but I don't see that in Vivaldi (Chrome 81) or Chrome Canary (Chrome 83)</del<.
Maybe version specific issue?

Confirmed in Vivaldi and Chrome Canary too.

**Comment by asamuzaK** [comment]
Found [1052872 - DevTools failed to parse SourceMap after recent update - chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=1052872)

**Comment by shaoran** [comment]
Strange, all other source maps from my webpack built project seems to work just fine with chrome. I'm using 80.0.3987.149 (Linux version).

**Comment by asamuzaK** [comment]
Confirmed in Chrome Canary too.
`HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME`

**Comment by asamuzaK** [comment]
Anyway, it's the issue of Chrome itself?

**Comment by asamuzaK** [comment]
Seems to track this issue [1053535 - Sourcemaps from chrome-extension:// URLs don't load - chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=1053535)

**Comment by asamuzaK** [comment]
I think there is nothing we can do on the extension side.
I'll close this.

**Comment by shaoran** [comment]
Sorry that it took me so long to reply, had a lot of work to do and in the meantime I've forgot about it.

> I think there is nothing we can do on the extension side.
> I'll close this.

Well, I think there is one thing actually. You could remove [line #2][1] from the
`browser-polyfill.min.js` file. But I understand if you don't want to make changes
to code from other libraries and I don't know whether the *Mozilla Public License*
would allow to make such a change and distribute it within this extension.

[1]: https://github.com/asamuzaK/withExEditor/blob/master/src/lib/browser-polyfill.min.js#L2

**Comment by asamuzaK** [comment]
If I do that, hash changes and the extension will be rejected.
[dispensary/hashes.txt at master · mozilla/dispensary](https://github.com/mozilla/dispensary/blob/master/src/hashes.txt)

**Comment by shaoran** [comment]
Oh, that's interesting. So do web browsers (or the app/extension stores) look up for these hashes and if they don't match, then extensions get rejected or simply not executed?

Well, I think you're right, there's nothing much you could do. I just started ignoring the warnings, I don't want to stop using this extension, it's awesome.

**Comment by asamuzaK** [comment]
See [Third Party Library Usage | Firefox Extension Workshop](https://extensionworkshop.com/documentation/publish/third-party-library-usage/)

**Comment by shaoran** [comment]
Thanks for the link. I've never developed extensions for web browser, that's why I'm not familiar with this process at all.
