### ISSUE TITLE
The plugin stopped working properly after the latest update.

### ISSUE THREAD

**Issue by epicbansh** [asamuzaK/withExEditor#139]
Today the plugin has updated to version 7.1.0 and this bug appeared. 

To reproduce, open any website, open your external editor from any textbox or textarea (even from the search bar at google.com), save some text and exit the editor. Then change this text in the box (or even delete it), switch to another tab in the browser, and return back. You'll see that the text you've just amended has been replaced with the previous value that came from the external editor. I also noticed that this happens not only after switching to another tab but in many other cases.

Needless to say that I've tried reinstalling and restarting both host and extension, updated the host to latest version 5.4.3, updated node.js to 12.18.3, disabled all other extensions in FF, but the bug still persists. I'm using Firefox 78.0.2 (64-bit) and Windows 10 Home x64.

Thanks in advance.

**Comment by asamuzaK** [comment]
Confirmed

**Comment by asamuzaK** [comment]
Released v7.1.1

**Comment by epicbansh** [comment]
Thank you, seems to work now. Really appreciate it!
