### ISSUE TITLE
Extra line endings inserted when editing Simplenote text

### ISSUE THREAD

**Issue by ddirks** [asamuzaK/withExEditor#144]
This is a follow-on to a bunch of issues recently fixed and closed, including:

- https://github.com/asamuzaK/withExEditor/issues/123
- https://github.com/asamuzaK/withExEditor/issues/134
- https://github.com/asamuzaK/withExEditor/issues/137
- https://github.com/asamuzaK/withExEditor/issues/138

and may be related to an issue I originally (mistakenly) reported on withExEditorHost regarding behavior when using the external editor with Simplenote:

- https://github.com/asamuzaK/withExEditorHost/issues/77

Currently I am looking at withExEditor 5.4.4 on Windows 64-bit. The behavior I see when editing a Simplenote note is that when I invoke the editor (gvim), extra newlines are inserted in the editor window, one extra newline per original line. The additional newlines are preserved when the text is re-inserted into the browser window. This is different from what happened when I originally reported the issue; in that issue, lines were entered into the editor window properly, but newlines were added when the text was re-inserted into the original browser window.

I see this behavior with Simplenote notes in both Firefox and Chrome.

I do not see the extra lines inserted when editing text from other web apps (I tested yahoo mail, gmail, todoist).

Thanks for all your work on this -- it appears to have been very complicated to untangle!

**Comment by asamuzaK** [comment]
@ddirks 
Released withExEditor v7.1.4 couple days ago.
Is it working as expected now?

**Comment by ddirks** [comment]
Yes! The withExEditor/gvim/Simplenote web combination is once again working for me, under both Firefox and Chrome. (Win10x64)

Thank you so much for working through all these issues...
