### ISSUE TITLE
Host not started on Ubuntu 20.04 and Firefox 84.0.2 (64-bit)

### ISSUE THREAD

**Issue by ogai** [asamuzaK/withExEditor#153]
The extension doesn't start the Host. The preferences window displays:
`Host Connection Disconnected`
I have the file `~/.config/withexeditorhost/config/firefox/editorconfig.json` and `~/.config/withexeditorhost/config/firefox/withexeditorhost.sh` with the content:
```
#!/usr/bin/zsh
/usr/bin/node /usr/local/lib/node_modules/withexeditorhost/index.js
```
I can start the Host on a terminal displaying:
`
C{"withexeditorhost":{"message":"getEditorConfig","status":"ready"}}
`
but still I get `Host Connection Disconnected` even after restarting Firefox.
I wonder how to debug this.

**Comment by asamuzaK** [comment]
please check  below

> NOTE: If you have enabled Mandatory Access Control (for example, AppArmor) for your web-browser, ensure the profile allows the withexeditorhost.sh script to be executed.

**Comment by asamuzaK** [comment]
Also make sure that there is host manifest
`~/.mozilla/native-messaging-hosts/withexeditorhost.json`

**Comment by asamuzaK** [comment]
@ogai Still in trouble?

**Comment by asamuzaK** [comment]
No reply.
I'll close this.
Feel free to reopen.
