### ISSUE TITLE
How to setup default edit filetype

### ISSUE THREAD

**Issue by becarepsol** [asamuzaK/withExEditor#154]
How would one go about setting up `markdown` as the default filetype when
editing text, right now the default seems to be `txt`.

**Comment by asamuzaK** [comment]
Currently only .txt is supported.
Let's support it in a future version.

**Comment by asamuzaK** [comment]
[Try build](https://github.com/asamuzaK/withExEditor/tree/master/dest)

* Open options page (click toolbar button or Ctrl + ALT + U).
* Add checks to `Select File Extension When Saving Temporary Files` and file extensions.
* Right click on editable element (e.g. textarea).
  New menu item should appear.
