### ISSUE TITLE
Uninstall the host

### ISSUE THREAD

**Issue by Saectar** [asamuzaK/withExEditor#160]
What would be the correct way to uninstall the host client?

Thanks

**Comment by asamuzaK** [comment]
Tell me your OS, and host is npm package or binary?

**Comment by asamuzaK** [comment]
And your browser.

**Comment by Saectar** [comment]
Binary
Windows 10 pro
Mozilla Firefox 99.0.1

**Comment by asamuzaK** [comment]
* remove binary
* remove config files
  C:\Users\YOUR_USER_NAME\AppData\Roaming\withexeditorhost
* remove registry
  HKEY_CURRENT_USER\SOFTWARE\Mozilla\NativeMessagingHosts\withexeditorhost

**Comment by asamuzaK** [comment]
resolved?

**Comment by Saectar** [comment]
Yes

**Comment by Saectar** [comment]
Yes.
