### ISSUE TITLE
Stylish support

### ISSUE THREAD

**Issue by maxigaz** [asamuzaK/withExEditor#17]
With the Firefox extensions Stylish and It's all text!, I can edit user styles with an external editor. I.e. if both are installed, when editing a style, an additional button appears on top with the label "Open in external editor".

However, there's no such button when It's all text! is replaced by withExEditor. (Edit: I'm using Firefox 50.0 under Manjaro Linux.) Therefore, I'm wondering if it's possible to implement this feature in this extension as well.

**Comment by asamuzaK** [comment]
I'm porting withExEditor to WebExtensions.
And in WebExtensions, content scripts only runs in "http", "https", "file", "ftp", "app" schemes.
[Match patterns - Mozilla | MDN](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/match_patterns)
I don't know Mozilla will implement "about" scheme in the future.
If they do, then I'll try to support Stylish.

**Comment by asamuzaK** [comment]
Note:
Bugs that seem to be related to this issue.

[1269456 – Add permission to allow extensions to load semi-privileged URLs](https://bugzilla.mozilla.org/show_bug.cgi?id=1269456)

[1280370 – contextMenus do not support other protocols (ex. 'magnet:*', 'acestream:*', 'sop:*')](https://bugzilla.mozilla.org/show_bug.cgi?id=1280370)

**Comment by asamuzaK** [comment]
Note:
[Firefox support · Issue #166 · stylish-userstyles/stylish-chrome](https://github.com/stylish-userstyles/stylish-chrome/issues/166)

**Comment by asamuzaK** [comment]
Note:
Add another bug that also seem to be related.
[1271354 – Support moz-extension: urls in MatchPattern](https://bugzilla.mozilla.org/show_bug.cgi?id=1271354)

**Comment by asamuzaK** [comment]
[unnamed.png](https://lh3.googleusercontent.com/6qS9thtCuv7DsUMq_lWyxD15fOr0SE9qCkakfaH6F3pfPWGexKJOpbguZUBglxYW83iwaL_7=s640-h400-e365)

Looking at this screenshot, edit page is provided by "chrome-extension" scheme, so if the bug mentioned above ([1271354 – Support moz-extension: urls in MatchPattern](https://bugzilla.mozilla.org/show_bug.cgi?id=1271354)) is resolved, it seems that withExEditor can be applied.
Plus Stylish need to be updated to WebExtensions.

**Comment by asamuzaK** [comment]
[1271354 - Support moz-extension: urls in MatchPattern](https://bugzilla.mozilla.org/show_bug.cgi?id=1271354 "1271354 - Support moz-extension: urls in MatchPattern") is marked as FIXED, but it is limited to it's own moz-extension: url, which means withExEditor can't be enabled in other extension's moz-extension: url.

Anyway, Stylish does not seem to be switched to WebExtensions?

**Comment by maxigaz** [comment]
> Anyway, Stylish does not seem to be switched to WebExtensions?

You're right, although I personally use [Stylus](https://add0n.com/stylus.html) now.

**Comment by asamuzaK** [comment]
Should I close this then?

**Comment by maxigaz** [comment]
It is fine by me, but I would be more interested in seeing it compatible with Stylus, which is already a WebExtension. Shall I create a separate issue for that?

**Comment by asamuzaK** [comment]
As mentioned above, you can not execute withExEditor on Stylus' edit page (it's moz-extension://).

It is possible to interact messages between addons using runtime.connect() or runtime.sendMessage(), though.
However, in this case, both add-ons need to correspond, so it may not be so easy.

Would you contact the author of Stylus and see if he/she is interested to correspond with withExEditor?

**Comment by asamuzaK** [comment]
I will close this
