### ISSUE TITLE
Truncated content with CodeMirror

### ISSUE THREAD

**Issue by FabriceSalvaire** [asamuzaK/withExEditor#176]
I am facing truncated content with the Wiki.js/CodeMirror markdown editor.
Content can be truncated at the end or at the beginning.
I found withExEditor implements code to handle CodeMirror instead of a textarea tag.

**Comment by asamuzaK** [comment]
So what do you want me to do?

**Comment by FabriceSalvaire** [comment]
I can try to debug, but I don't have any experience with Firefox extension.

I guess the magic is done here https://github.com/asamuzaK/withExEditor/blob/master/src/mjs/live-edit.js

I found a cut/paste in CodeMirror is a workaround to edit content with Emacs.

**Comment by asamuzaK** [comment]
Please tell me the URL where the issue can be reproduced, and steps to reproduce it.

**Comment by asamuzaK** [comment]
Closing for now.
Feel free to reopen with additional info.
