### ISSUE TITLE
Trigger change event

### ISSUE THREAD

**Issue by smlx** [asamuzaK/withExEditor#26]
Hi,

Great addon, I've recently switched from It's All Text due to e10s support :+1: 

One bug I've run into is that the addon doesn't trigger the change event on a textarea. This is required for some web apps that only grab the contents of a textarea on change. The change event doesn't fire automatically if the contents of a textarea is updated via javascript.

To work around this bug, please manually trigger the change event on a textarea after updating its contents.

Thanks!

**Comment by asamuzaK** [comment]
Those apps should listen to `input` event instead, I suppose?
[input - Event reference | MDN](https://developer.mozilla.org/en-US/docs/Web/Events/input)

**Comment by asamuzaK** [comment]
Ah, confirmed.
`input` event is not fired neither.

**Comment by asamuzaK** [comment]
Dispatching `input` event will be OK for those apps?

**Comment by asamuzaK** [comment]
Test release, please try.
v2.1.0a1
[withExEditor :: Versions :: Add-ons for Firefox](https://addons.mozilla.org/en-US/firefox/addon/withexeditor/versions/beta)

**Comment by smlx** [comment]
I tried to test the new version, but the web app that I was testing this with is affected by  asamuzaK/withExEditorHost#3

**Comment by asamuzaK** [comment]
I'll close this issue as resolved.
If you still have it, please reopen.
