### ISSUE TITLE
Cannot get this to work with emacsclient

### ISSUE THREAD

**Issue by ghost** [asamuzaK/withExEditor#28]
I am trying to use this with emacsclient with no success so far.

I tried using it out of the box, just putting /usr/local/bin/emacsclient as the the editor, with no command line options, and not running it it in a shell, and that didn't work. More specifically, when I try to use the addon to edit a text area in emacs, it does open a new buffer (named /tmp/withExEditor/Unnamed), but I have the following problems:

1. The preexisting contents of the text area is not copied to the emacs buffer.
2. When I save the buffer in emacs, the text is not copied back to the text area. (Obviously, this is a showstopper.)
3. When I press C-x # in emacs to close the buffer, it dumps me into a new empty buffer named ~/Profile.
4. When I press C-x # to close *that* buffer, it dumps me into a new empty buffer with the name /home/myusername/1/tmpFiles/-3-32/github.com/withExEditor961017_505. This buffer closes normally.
5. If I try to edit text from another text area, it again opens a buffer /tmp/withExEditor/Unnamed. This time the buffer contains any text that I wrote during my previous attempt, but still doesn't contain any of the preexisting contents of the text area, and it still doesn't copy back to the text area.

I also tried the suggestion of somebody who posted a review of your addon, to use an auxiliary shell file to call emacsclient with the options -c -a "" "$@" and with some other specific options checked/unchecked in the addon config menu. Other than the buffers opening in a new emacs frame instead of the existing one (because of the -c flag), the behavior was exactly the same.

If it's helpful, I am using withExEditor 1.9.0 on Firefox 52, 64-bit, on Ubuntu 16.04. I am happy to provide any other information if it might be helpful to you. This addon looks promising and I really appreciate your work on it.

**Comment by asamuzaK** [comment]
Hi, I'm requesting a review to AMO for v2.0.0, but still in a long long waiting list, though.
I'm not intended to fix 1.9.0 anymore.

You can get a pre-release for 2.x
Current version is 2.1.0a4
[withExEditor](https://addons.mozilla.org/en-US/firefox/addon/withexeditor/versions/beta)
You will need a host too.
[asamuzaK/withExEditorHost](https://github.com/asamuzaK/withExEditorHost)

1. Uninstall withExEditor 1.9.0 (Do not overwrite, old settings will remain)
2. Install 2.1.0a4
3. Setup host etc.

Tell me what happens with it.

Thanks

**Comment by ghost** [comment]
Thanks for getting back to me. I will try out the newer version when I get
a chance and post my experience on the github page. It may be a little
while though, I'm pretty busy these days.

Cheers,
Matt

**Comment by asamuzaK** [comment]
[Issue #23](https://github.com/asamuzaK/withExEditor/issues/23#issuecomment-287579373 "Try out new withExEditor which embedded WebExtensions · Issue #23 · asamuzaK/withExEditor")
