### ISSUE TITLE
Editor Config Path not being saved

### ISSUE THREAD

**Issue by benyakov** [asamuzaK/withExEditor#29]
The withExEditorHost is set up and seems to be functioning, but withExEditor is not saving the value in Editor Config Path. I am using the full path of the editorconfig.json file, and have tried it in various locations. Now it is at "/home/jesse/withExEditorHost/config/editorconfig.json". This is apparently not recognized as a valid path, because the Editor Label option remains disabled.

Other options are saved as expected, like the icon, the Access Key, and the check boxes below.

This is Firefox 52.0.1 on Ubuntu. I have tried disabling all other extensions.

**Comment by asamuzaK** [comment]
Any logs in browser console (Ctrl + Shift + J)?
Also check withexeditorhost.sh has executable bit, if not, add it.

**Comment by benyakov** [comment]
This is repeated several times in the browser console:

```
Error: Attempt to postMessage on disconnected port
Stack trace:
portHostMsg@moz-extension://34bb9eec-1fd6-4863-9330-921004b1b040/js/background.js:152:20
handleMsg@moz-extension://34bb9eec-1fd6-4863-9330-921004b1b040/js/background.js:547:25
handlePort/<@moz-extension://34bb9eec-1fd6-4863-9330-921004b1b040/js/background.js:599:41
background.js:83:5

```

withexeditorhost.sh is executable (was 0755, now 0777).

**Comment by asamuzaK** [comment]
Save "withexeditorhost.json" in
```
~/.mozilla/native-messaging-hosts/withexeditorhost.json
```

**Comment by asamuzaK** [comment]
Also see [issuecomment-287431132](https://github.com/asamuzaK/withExEditor/issues/23#issuecomment-287431132 "Try out new withExEditor which embedded WebExtensions · Issue #23 · asamuzaK/withExEditor") and below.

**Comment by benyakov** [comment]
It works!
I fixed two things. Not sure which was causing the console error I posted earlier.

- In withexeditorhost.sh, I included the full path to node as you suggested in the other comment thread.
- I fixed a syntax error in editorconfig.json in the "cmdArgs" value.

Thank you for your help. This extension is exactly what I was hoping for.

**Comment by asamuzaK** [comment]
Glad to hear that.
Can you help updating host setup instuctions?
[#4](https://github.com/asamuzaK/withExEditorHost/issues/4 "Update host setup instructions · Issue #4 · asamuzaK/withExEditorHost")
WIP PR [#5](https://github.com/asamuzaK/withExEditorHost/pull/5 "Add troubleshooting section by asamuzaK · Pull Request #5 · asamuzaK/withExEditorHost")
