### ISSUE TITLE
"TypeError: this._recipeManager is null" is logged

### ISSUE THREAD

**Issue by asamuzaK** [asamuzaK/withExEditor#4]
"TypeError: this._recipeManager is null" is logged in browser console when clicking "Open Add-on Manager" from the toolbar button.
Depends on 1167872 – Error: TypeError: this._recipeManager is null Source file: resource://gre/modules/LoginManagerParent.jsm Line: 118/185 https://bugzilla.mozilla.org/show_bug.cgi?id=1167872

**Comment by asamuzaK** [comment]
Also logged when right click in input[type=text|email|tel|url].
But not in input[type=search], nor textarea.

**Comment by asamuzaK** [comment]
Released v1.8.0
You should update manually from beta.
Thanks.
[withExEditor :: Add-ons for Firefox](https://addons.mozilla.org/en-US/firefox/addon/withexeditor/)

**Comment by asamuzaK** [comment]
This error seems to be gone in WebExtensions.

**Comment by thecircleoflifefree** [comment]
Could you expand a bit on the browsers tested if several? I get it when pressing 'Enter' on an input field.

**Comment by asamuzaK** [comment]
I don't remember until when or which version I last saw that error.
Maybe around 52, but not sure.
