### ISSUE TITLE
Problem with editing (source) on  Wikipedia

### ISSUE THREAD

**Issue by denniz-j** [asamuzaK/withExEditor#47]
Hi asamuzak,
Thanks for working on withExEditor, a great tool.

However, withExEditor does not seem to work with Wikipedia's  "Preview"  system.

Steps to reproduce problem...

1. go to https://en.wikipedia.org/wiki/Wikipedia:Sandbox
2. click a link to 'Edit Source'
3. click the "Preview" button below the edit box
4. In the edit box right click and choose the "Edit text with xxxxx ( your External text editor)"
5. make some edits and save in the external editor
6. go back to the Wikipedia sandbox page and click the "Preview" button below the edit box
7. Now go back to your external editor and make further edits and save them
8. These further edits do not get transferred back into the edit box.

Could you please comment on this problem?
thanks
Dennis

**Comment by asamuzaK** [comment]
That's because the page get refreshed each time when you press Preview button.

So, after you pressed Preview, you need to right click on the edit box again and select "Edit Text with ...", or press "Ctrl + Shift + u" on the edit box.

**Comment by denniz-j** [comment]
Thanks for the work-around asamuzaK. It works on the Wikipedia site e.g. https://en.wikipedia.org/wiki/Wikipedia:Sandbox 
Unfortunately, does not work on my private wiki. 
Identical browser, Firefox, identical withExEditor and withExEditorHost versions, different Mediawiki versions at the backend running the websites. Will see if it comes good after I update our Mediawiki software, in the next month or so.
Thanks.
