### ISSUE TITLE
Clarifiy why Host Version is incompatible

### ISSUE THREAD

**Issue by i5513** [asamuzaK/withExEditor#48]
Is linux supported for this extension?

On Debian appear:
Host Connection Disconnected
Host Version Incompatible

It will not work if you restart firefox

Any workaround?

**Comment by asamuzaK** [comment]
Download the latest host (current v2.1.0) and run setup.js again.
[Release v2.1.0 · asamuzaK/withExEditorHost](https://github.com/asamuzaK/withExEditorHost/releases/tag/v2.1.0 "Release v2.1.0 · asamuzaK/withExEditorHost")
Note that node.js v8 or later is required.

```
> cd /path/to/host
> npm install
> node setup.js
```

**Comment by asamuzaK** [comment]
Oh, I'm sorry, I just found that I forgot to write about node.js version in release note.

**Comment by i5513** [comment]
now it is working, but is possible to add a keyboard shortcut, so no mouse is use ?

Thank you !

**Comment by asamuzaK** [comment]
> now it is working, but is possible to add a keyboard shortcut, so no mouse is use ?

Click toolbar button and open options page.
You can configure short cut key.
