### ISSUE TITLE
Emacs client support

### ISSUE THREAD

**Issue by FabriceSalvaire** [asamuzaK/withExEditor#49]
Look like we could connect directly to **emacs client**, cf.

* https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Native_messaging
* https://github.com/mdn/webextensions-examples/tree/master/native-messaging

Would it be possible to have several options to perform native messaging ?

**Comment by asamuzaK** [comment]
Execute emacs client from the host (set emacs client as an editor in setup.js).

**Comment by asamuzaK** [comment]
What do you want in this issue?
* a help for setting up the host for emacs client
* a feature request that you wish the host to start an emacs client directly
* other

**Comment by asamuzaK** [comment]
Seems no reply, I will close this issue.
Reopen if there is additional info.
