### ISSUE TITLE
(feature request) phone version possible?

### ISSUE THREAD

**Issue by Eli-the-Bearded** [asamuzaK/withExEditor#51]
Now that it works for me, I'm curious if you think this can be made into a phone version.

* I've got Firefox on Android. In the Mozilla add-ons site this is listed as incompatible for that FF.
* I can see how the withExEditorHost might be tricky to install for people used to using phones as GUI slabs.
* But I've got node.js and vim installed *already* on my phone. 

Issues I see:

* I'm not using a rooted device, limiting my ability to directly edit Firefox files on "disk".
* Android has every app run as a separate user, raising questions of how the processes might communicate.
* Firefox for Android might not even have the API / features you need compiled in.

Since you wrote this, you probably have a much better understanding of the challenges here. What do you think?

**Comment by asamuzaK** [comment]
I myself want this feature, but Google does not allow extensions in mobile Chrome, so I think there is no native messaging API in Android.
