### ISSUE TITLE
Can't get it working with Firefox Quantum 57.0 (64-bit)

### ISSUE THREAD

**Issue by wdenx** [asamuzaK/withExEditor#52]
Running under Fedora 26 with all current updates:
firefox-57.0-2.fc26.x86_64
nodejs-6.11.5-1.fc26.x86_64
Installed using the Firefox Add-ons manager.  No error messages.

In the "Preferences" page I see
   Host Connection Disconnected
   Host Version  Incompatible
   Editor Label  <disabled>
Reload and repeated restart of firefox does not help.

**Comment by asamuzaK** [comment]
Update Node.js to v8.x and run below

```
cd path/to/host
npm install
node setup.js
```

**Comment by asamuzaK** [comment]
See also [Problem Installing on Debian Stretch · Issue #13 · asamuzaK/withExEditorHost](https://github.com/asamuzaK/withExEditorHost/issues/13#issuecomment-345655611 "Problem Installing on Debian Stretch · Issue #13 · asamuzaK/withExEditorHost")

**Comment by asamuzaK** [comment]
@wdenx 
Still in trouble?

**Comment by asamuzaK** [comment]
Seems no reply, I will close this issue.
Reopen if you still have trouble.
