### ISSUE TITLE
Firefox Containers and HTTP Authentication

### ISSUE THREAD

**Issue by chriscroome** [asamuzaK/withExEditor#53]
I suspect this isn't an issue specific to withExEditorHost but is a more general issue with Firefox, however it might be worth flagging it up to users — if you have a site open in a Firefox container and it uses HTTP Authentication, when you right click "edit with" in a textarea you get the HTML source of the 401 Unauthorized page rather than the content of the textarea.

I have had a quick look on [bugzilla](https://bugzilla.mozilla.org/) for an issue that covers this but didn't find one.

**Comment by asamuzaK** [comment]
Maybe another permission "contextualIdentities" will be needed?

**Comment by asamuzaK** [comment]
Would you give me more info?

* In the first place, other than Authed sites, can you use withExEditor even if the page is opened in the container tab?
* Authed site is `https`, or normal `http`? And, is there a difference in behavior between `http` and `https`?

Thanks.

**Comment by chriscroome** [comment]
I have just done some more testing and with Firefox 57 on Linux and I can't now reproduce this bug at all, everything seems to work without a problem, you can test this [here](https://firefox.webarch2.co.uk/).

With Firefox Developer Edition 58.0b withExEditor doesn't appear to work at all (the extension installs but right clicking doesn't give you an withExEditor edit option) so I couldn't test using that browser.

**Comment by chriscroome** [comment]
I have just tested on another machine and didn't have a problem with either Firefox Developer Edition 58.0b or Firefox 57.0 (both on Linux) &mdash; I can't reliably reproduce this issue so I'm going to close this bug.
