### ISSUE TITLE
Make passing filename to edit to the editor the default configuration

### ISSUE THREAD

**Issue by DMcCunney** [asamuzaK/withExEditor#54]
As mentioned in my review on the Moziila Addons site, I needed to modify my original withExEditor configuration to specify passing the filename to be edited to my configured editor to get the expected behavior when trying to edit text to be posted in a text box on a site.  I made the change by editing the editor config JSON file and changing that setting from _false_ to _true_.

I installed withExEditor primarily to replace the functionality lost when the deprecated _It's All Text!_ extension stopped working, and I suspect most other users will have a similar motivation.  Things like opening View Source in the editor are a fringe benefit I don't expect to use often.

Given that, I think having that setting default to _true_ when withExEditor is installed will reduce friction for users.  Needing to install node.js as a prerequisite and configure it before you can install withExEditor makes withExEditor a power user's tool.   _It's All Text!_ was simple - install it, tell it what editor to use, and you were done.  Mozilla's requirement of a host process on the user's machine communicating with the site you are visiting to be able to edit text locally for posting on the site raises the bar.  That's a requirement you're stuck with, but anything that reduces what the user must configure to get things working is a boon.

(And along those lines, it would be nice if that config change could be made from the options page withExEditor displays to the user when they select it in the Addons list and click Options.)

I'm thinking about other ways it might be possible to ease installation and setup.  I'll open another issue if one occurs to me.

Meanwhile, thank you for withExEditor.  IT fills a big hole here.

**Comment by asamuzaK** [comment]
> Given that, I think having that setting default to true when withExEditor is installed will reduce friction for users.

It depends on the text editor.
Some editor requires file path to be right after the executable (put as first command arg).
Some editor requires it to be the last.

Considering the light users who don't know much about command lines, I decided that it would be better to default to false.

> it would be nice if that config change could be made from the options page withExEditor displays to the use

It was, until v3.x
Someone pointed out security risks, so I removed them.
See [Editor configuration trusts the browser side too much · Issue #15 · asamuzaK/withExEditorHost](https://github.com/asamuzaK/withExEditorHost/issues/15 "Editor configuration trusts the browser side too much · Issue #15 · asamuzaK/withExEditorHost")

I think that you should be able to change the settings of the editor more easily, though.

**Comment by asamuzaK** [comment]
By the way, `fileAfterCmdArgs` is a boolean value where to put file path.
If `true`, the command will be at the last: editor.exe -a -b path/to/file
If `false`, it will be the first: editor.exe path/to/file -a -b

**Comment by asamuzaK** [comment]
```
Put file path after command arguments? [y/n]
```
Perhaps it is hard to understand with this expression?

**Comment by asamuzaK** [comment]
Added note about file path option.
[Add note about file position option · asamuzaK/withExEditorHost@f7122b3](https://github.com/asamuzaK/withExEditorHost/commit/f7122b3b3227df5037668567fc6e471fcf5e6c8c "Add note about file position option · asamuzaK/withExEditorHost@f7122b3")
Will this make sense?

**Comment by asamuzaK** [comment]
Another one told me that he had the same issue.
No command line options set, but failed to spawn the editor, when fileAfterCmdArgs is `false`.
Maybe there is a bug when spawn child process.
I'll look into my module.

**Comment by asamuzaK** [comment]
Another user told me that it happened with EmEditor.
I tried with that, but could not confirm.
It worked fine even if fileAfterCmdArgs is false.

@DMcCunney 
Could you tell me about your editor?
If you set to `false` again, do you see any error logged in browser console? (Ctrl + Shift + J)

**Comment by asamuzaK** [comment]
I looked back over the code, but I did not see any problems.

Unless command line options are specified, file path is the only argument, so it does not matter whether the file position value is set to true or false.

The reason why the editor did not start is probably that a temporary file was not created for some reason.
However, in that case, it should be logged in the browser console.

I will mark as invalid and close the issue.
Feel free to reopen if you have additional info.

Thanks.
