### ISSUE TITLE
Issues with "withExEditor"

### ISSUE THREAD

**Issue by JontAlle** [asamuzaK/withExEditor#61]
I dont know where to start.
1) the developer asamuzaK keeps telling me to write an "issue" but I dont know what that means. Well it means adding something here on GitHub. Well I'm not a GitHub user. Its nice for Asamuzak but not for anyone else. If you want read the reviews you need to read them (along with my extensive comments, and others) at:
   https://addons.mozilla.org/en-US/firefox/addon/withexeditor/reviews/

This is very important software, and it does work, but the DOCs are next to useless, and you can read about on the Mozilla reviews website.

There are a number of minor issues that need to be fixed, but it does work, as is.
BTW, dont waste your time with "GhostText" an advertised alternative.  I have Latex commends and it garbled them.  It is only usable for the simplest of cases. Best you get "withExEditor" working. Maybe the comments on Mozilla reviews can help you do this.

Thanks for your work asamuzaK. Your work saved my life.

**Comment by asamuzaK** [comment]
I do not speak English natively, and I am aware that I am not explaining features sufficiently.
If you like, please write the document proposal here.

And about the `u` key.
It is a key for shortcut.
Put a check in the option below (`Enable Shortcut Key To Execute The Editor Directly`), then you can execute your editor without going through context menu when you press `Ctrl + Shift + u`.
You can change the key within the range of `a` to `z` if you want, but note that modifiers (Ctrl key and Shift key) can not be changed.

Thanks.

**Comment by epicbansh** [comment]
Well, so why it is impossible to make a wider choice of these editor hotkeys? Is it some kind of browser restriction that can't be overcome? It would be nice if we were able to select any hotkey, not only letters with CTRL+SHIFT

**Comment by asamuzaK** [comment]
I think that key assignment customization should be made as an API of WebExtensions.
There are some bugs in Bugzilla, but not landed yet.
refs: [1303384 - UI for re-assigning command shortcuts](https://bugzilla.mozilla.org/show_bug.cgi?id=1303384 "1303384 - UI for re-assigning command shortcuts"), [1421811 - Provide a way for an extension to update the shortcut for its command](https://bugzilla.mozilla.org/show_bug.cgi?id=1421811 "1421811 - Provide a way for an extension to update the shortcut for its command")

Current hotkey implementation is a workaround until then, so I want to keep it simple as possible.

**Comment by JontAlle** [comment]
I use gvim, which is working fine. However there is an important difference between "withExEditor" and the older "its all text":
With "Its All Text" when I was in vi, I could do a save from gvim  (:w) and it would update the webpage. That function does not work. The only way to write the data is to ZZ (write and quit).  

Is there any way to allow :w send the edits to the webpage. This greatly enhances the utility as you can save, verify, edit, save verify, edit, without leaving closing VI.

Perhaps there is a different vi command that would save the changes so they are written back to the webpage. For example would :w! cause the web page to be updated?

**Comment by asamuzaK** [comment]
Save the text, leave your editor open, move focus to the textarea of ​​the website, is the saved result not reflected?

**Comment by asamuzaK** [comment]
Customizing key assignment feature is implemented in Firefox 66.
I'll close this issue.
