### ISSUE TITLE
DOM node reload bug

### ISSUE THREAD

**Issue by epicbansh** [asamuzaK/withExEditor#63]
Here's the example to reproduce the issue: https://jsfiddle.net/k2LLeqyz/6/

When you start the external editor first, everything works fine. But after you press "Replace DOM node" button, the plugin stops working. It still opens the text area contents in the editor, but is unable to put them back to textarea.

**Comment by asamuzaK** [comment]
Thanks for the test case.
Confirmed.

**Comment by asamuzaK** [comment]
Try build.
[v4.2.2a2](https://addons.mozilla.org/firefox/addon/withexeditor/versions/beta)

**Comment by epicbansh** [comment]
wow, it works! Thank you so much. Maybe I'll give another chance to new Firefox!

**Comment by asamuzaK** [comment]
Released [v4.2.2](https://addons.mozilla.org/firefox/addon/withexeditor/)

Note that beta version will not update automatically to release version.
You need to update yourself.
