### ISSUE TITLE
Latest update - plugin doesn't work

### ISSUE THREAD

**Issue by epicbansh** [asamuzaK/withExEditor#67]
I'm sorry to bother you, but after today's update the plugin stopped working at all. It says that Host Connection/Version is Unknown. I've tried reinstalling latest host version 2.2.5, but nothing changed. Previous plugin version still works fine if you don't update it.
Thanks in advance

**Comment by michael-776** [comment]
Same problem here. I also switched back to previous version and that's working.

That's with firefox 58.0.2 and node node-v8.9.4,  linux-x64

Possibly helpful:
TypeError: Argument 1 of PrecompiledScript.executeInGlobal is not an object.[Learn More]  ExtensionContent.jsm:357:18
sender.tab is undefined  main.js:585
Error: WebExtension context not found! ExtensionParent.jsm:830:13

**Comment by asamuzaK** [comment]
Should be fixed in [Revert commands · asamuzaK/withExEditor@81172b1](https://github.com/asamuzaK/withExEditor/commit/81172b1e8216b16c90e0cf1c2df7f05c296ca034 "Revert commands · asamuzaK/withExEditor@81172b1")

**Comment by asamuzaK** [comment]
Released [v4.2.5](https://addons.mozilla.org/firefox/addon/withexeditor/)
Thanks for your reports.

**Comment by michael-776** [comment]
I updated to  v4.2.5 -- working fine, thank you
