### ISSUE TITLE
Requesting ability to hide "view source with..."

### ISSUE THREAD

**Issue by ssokolow** [asamuzaK/withExEditor#7]
I only use withExEditor as a way to edit form data and my context menu is cluttered enough as-is. Please add a preference to disable the "view ... source with..." options.

**Comment by asamuzaK** [comment]
I'll make a try, but it may not be that easy.

**Comment by asamuzaK** [comment]
Merged [Enable only on edit texts #8](https://github.com/asamuzaK/withExEditor/pull/8)

**Comment by ssokolow** [comment]
Thanks. :smile:

**Comment by asamuzaK** [comment]
Released on Development Channel (1.6.0-b3)
Please try it.
[withExEditor :: Versions :: Add-ons for Firefox](https://addons.mozilla.org/ja/firefox/addon/withexeditor/versions/)

**Comment by ssokolow** [comment]
It seems to work perfectly, but you might want to change the English label since its meaning is unclear to native English speakers.

Since I have some free time right now, here are a few alternatives which _would_ feel natural to native English speakers, complete with in-depth explanations...
1. **Enable only for text entry fields**
   
   This is an alternative way to write "Only enable withExEditor for text entry fields" and would be the most direct translation of what you wrote.
   
   Since I have a very good grasp of the English language, I'll explain the issues with what you wrote:
   - **Use:** Native English speakers think of showing a menu item as "give me the _option_ to use...", so writing "Use" implies automatically triggering the external editor rather than waiting for the user. 
     
     "Enable" is a better word, since "enable me" means "make me able to" and it's commonly used in other programs, so users will be familiar with it.
   - **Edit Text Mode:** Native English speakers don't think of focusing a widget or field as changing the "mode", so saying "Edit Text Mode" is confusing. (It makes it sound like "Edit Text Mode" should be similar to the caret-browsing mode accessible by pressing `F7` but with the ability to actually alter the page's contents.)
     
     The natural English term for all places you can edit text within a web page is "text entry fields" and English speakers won't be picky about which preposition you use.
     - "for text entry fields" ("Enable X for Y" is a common English construction in technical writing.)
     - "on text entry fields" (Menus and menu entries can be thought of as hanging on other parts of the GUI like branches and leaves on trees)
     - "in text entry fields" (When the cursor is _in_ the text entry field)
     - "inside text entry fields" (Less consice but, in this case, the same thing as _in_)
     - "with text entry fields" ("Enable X with Y" is one way to say "Make it possible to use X with Y")
   - **Only:** It usually feels more natural to put "only" at the beginning rather than the end. The simplest, most obvious natural English sentence would be "Only enable for text entry fields" (short for "Only enable withExEditor for text entry fields") but I was taught to put words like "Enable" as close as possible to the beginning and "Enable only for text entry fields" is also good because the kind of written English used in GUIs allows you to add "only for text entry fields" after a statement like "Enable withExEditor" and then omit the subject (withExEditor) when it's obvious.
2. **Hide "View Source with..." options**
   
   Another simple, clear way to explain what will happen. Native English speakers will recognize that you're using "View Source with" to mean all of the variants of "View ... Source with".
   
   I'm not 100% sure why I use the word "options" but here's what I've managed to determine:
   - "menu entries" would be the most accurate term, but it's too technical to feel natural to many users.
   - "commands" would probably feel natural to most users, but it feels **very** wrong to technical users, who associate "command" with what you'd type into `cmd.exe` or `/bin/sh`.
   - "options" isn't the ideal term, but it's easy for everyone to understand (a menu is a set of options for you to choose from) and it won't feel wrong to technical users.

I wouldn't use `Show only the "Edit text with..." option` because users may think that it will remove the toolbar button.

**Comment by asamuzaK** [comment]
Thanks.
I've updated the title.

**Comment by asamuzaK** [comment]
How about `Activate only for editing texts`
Does this feel natural ?

**Comment by ssokolow** [comment]
"Activate" has the same problem as "use". (it feels like it should be referring to the external editor because the extension itself will always be "active" unless the user asks Firefox to disable it and, when you talk about menu items, "activating" them is clicking on them.)

In fact, on the technical side, it's worse than "use" because some GUI systems like the GTK+ toolkit actually have an "activate" signal on clickable widgets which has a similar meaning to the "clicked" signal.

"for editing texts" is harder to read because, when you look only at the grammar, "editing" could be an adjective, so it takes an extra step (recognizing that there's no such thing as "an editing text") to make sense of it. (For example, in some English-speaking countries, "whipping cream" is a type of cream, so "for whipping cream" could mean "to be used to whip cream" or "for use with 'whipping cream'")

"texts" is wrong because the word "text" has different meanings depending on whether you're using it as a countable noun like "bottle" or an uncountable noun like "sand". ("A text" is a specific piece of writing like the Signet Classics edition of Mary Shelley's Frankenstein on my bookshelf, while "text" is general in the same way that "sand" is. You can't say "I want a sand" because it's uncountable.)

The most similar correct version would be "Show only when editing text".

**Comment by ssokolow** [comment]
I just noticed one other problem. "Show only when editing text" is unclear because "Show withExEditor only when editing text" is unclear. (Show what? The menu item? The toolbar button? Something else?)

You'd have to say "Show menu item only when editing text".

I suggested "Enable only when editing text" because "Enable withExEditor only when editing text" makes sense.

**Comment by ssokolow** [comment]
The difference between "Enable" and "Activate" is that "Activate" roughly means "trigger" but can't mean "allow" on its own, while "Enable" roughly means "allow" and can't mean "trigger" on its own.

Activate the process. = Enable the process to proceed.

(Activating the process is like pushing a ball to start it rolling down a hill. Enabling the process to proceed is like removing a piece of wood that is preventing the ball from rolling.)

Enable the menu item. = Activate display of the menu item.

(Enabling the menu item is making it possible for it to appear. Activating display of the menu item is taking action to show it.)

**Comment by asamuzaK** [comment]
"Enable only when editing text"
I'll use this for the title.
Thanks a lot.

**Comment by ssokolow** [comment]
Glad I could help.

**Comment by asamuzaK** [comment]
Updated the title, and released v1.6.0-b4
Closing.

**Comment by asamuzaK** [comment]
Released v1.6.0 [withExEditor :: Add-ons for Firefox](https://addons.mozilla.org/ja/firefox/addon/withexeditor/)
