### ISSUE TITLE
Does not work any more

### ISSUE THREAD

**Issue by fpoto** [asamuzaK/withExEditor#73]
I have 4.2.6 installed. I have used withExEditor since 4 January.  Last time I used it maybe one month ago and it worked. Now, on Firefox running on Debian, if I right click on the window where I'm writing and choose "Edit Text with editor" nothing happens.

I have restarted Firefox just to be sure, but nothing changes.

I don't know where to start looking to find out what's wrong.

**Comment by asamuzaK** [comment]
Please check below.
* Open browser console, Ctrl+Shift+J
  Is there any logs related to withexeditor or host?
  You can filter logs by adding keyword `withexeditor` on the up right corner.
* Open options page from about:addons
  Is host connected? Is host version compatible?

**Comment by fpoto** [comment]
I went to the console, pressed the right button and this message appeared:

>   TypeError: realSpellChecker is null

I close the context menu, I pressed the right button again, no message appeared in the console.  Now everything works...

Thank you, should it happen again I'll try the console first and report it.

**Comment by asamuzaK** [comment]
So, not related to withExEditor?

**Comment by asamuzaK** [comment]
I will close this.
If it still happens, feel free to reopen.
Thanks.

**Comment by fpoto** [comment]
I don't know if it was related to withExEditor, maybe not.
Thank you for your time.
I suggest that the trick of opening the console and looking for error messages be written somewhere, maybe in a Debug section, or in a FAQ section.

**Comment by asamuzaK** [comment]
> I suggest that the trick of opening the console and looking for error messages be written somewhere, maybe in a Debug section, or in a FAQ section.

Added notification option #76
