### ISSUE TITLE
Won't save text into edit field

### ISSUE THREAD

**Issue by MarkRunyan-3DS** [asamuzaK/withExEditor#79]
Finally had set up so external editor (gvim) is invoked with current contents of edit field.
Made changes in editor, saved changes, and exited editor.  Changes were NOT put into the edit field.

WIndows: W7 Enterprise SP1
Browser: 59.0.2(64 bit)
gvim: version 7.3
Extension:  withExEditor  (I could not find version info)
Additional code: withExeditorHost index program  (I could not find version info)

**Comment by asamuzaK** [comment]
Please check below

* Open browser console (Ctrl + Shift + J).
  Is there any error related to withExEditor or withExEditorHost?
* Open task manager (Ctrl + Alt + Del) and look into Firefox process.
  Is Node.js process running as a child process?
  Maybe you can find Node.js process in the background process list.

**Comment by asamuzaK** [comment]
One note.
In the current version, edited text will not be synchronized unless you move focus to the text area.
This behavior has been fixed in the next edition.

**Comment by asamuzaK** [comment]
@MarkRunyan-3DS 

Still in trouble?

**Comment by MarkRunyan-3DS** [comment]
Only because I have not yet followed up on the issue.  I had to switch to another browser to get work done.
I will be back to this (especially if it is as simple as setting focus).

Best Regards,

Mark RUNYAN

R&D, Spatial, Release Engineer

**Comment by MarkRunyan-3DS** [comment]
In reviewing the information you originally sent, I can confirm that I do not have node.js running.  You may close this issue report as “user error”.
I will continue to try to use this extension, but there is no issue if I failed to install correctly.
Thank you for your time.

Best Regards,

Mark RUNYAN

R&D, Spatial, Release Engineer

**Comment by asamuzaK** [comment]
OK, please re-open this issue if you find anything wierd.

FYI, you can try pre-release of withExEditor.
[v5.0.0rc1](https://github.com/asamuzaK/withExEditor/tree/master/dest "withExEditor/dest at master · asamuzaK/withExEditor")

**Comment by asamuzaK** [comment]
PS
Personal information such as a telephone number was included in your replies, so I deleted that part.
