### ISSUE TITLE
incorrect view-source with pwd-protected laravel page

### ISSUE THREAD

**Issue by ghost** [asamuzaK/withExEditor#83]
[config-files-and-view-source-files.zip](https://github.com/asamuzaK/withExEditor/files/2042356/config-files-and-view-source-files.zip)
does not load correct view-source data into notepad++. 
see _view-source_actual.html vs. _view-source_withExEditor.html.
source is password protected laravel page.
interesting that view-source on chrome looks like _view-source_withExEditor.html AFTER running withExEditor, but looks like _view-source_actual.html BEFORE running withExEditor, even though page looks correct in both cases.
!! would be great ext. if it worked in my case !! hope you can fix it !!

**Comment by asamuzaK** [comment]
In the case of "View Source with ...", the file is fetched from the server.
It looks like that The server refused fetching the file for some reason and got the source like that?
I'm not sure though.

FYI, if you want to display the current source, for example, including content added by scripts etc, try `Ctrl + A` (select all) and then choose "View Selection Source with ...".
Note that it only shows source of `<body>` and descendants.

**Comment by asamuzaK** [comment]
What do you get if you set debug mode value to `true`?
[laravel/app.php at master · laravel/laravel](https://github.com/laravel/laravel/blob/master/config/app.php#L42 "laravel/app.php at master · laravel/laravel")

**Comment by ghost** [comment]
with debug = true, i get the detailed laravel stack trace, which is the same thing as the file i sent you, except with detailed errors. this is not the correct view-source either, since the page renders correctly in the browser. 
i see a lot of session errors in the debug stack trace. is your app using my session data when it requests the view-source from my server? if not, that would account for the error. do you know if your app works on other password protected websites? i'm not sure how chrome itself gets the view-source data. does it actually make another request of the server? if so, it must use my session data.
thanks for your quick response. i appreciate your help.
your app would be a big help to me if we can get it working.

**Comment by asamuzaK** [comment]
Ah, you mean it is protected per page, right?
I have never tested that case.

BTW, do you have Firefox installed?
If you do, please try [v5.1.0a3](https://github.com/asamuzaK/withExEditor/tree/master/dest "withExEditor/dest at master · asamuzaK/withExEditor")

**Comment by ghost** [comment]
i don't mean that each page is separately password protected, i mean that the entire site is behind a one-time (until cookies are cleared) login.
i just added your app to firefox and opened three pages in firefox: 1) default google search page, 2) my logged-in amazon aws ec2 instances page (https://console.aws.amazon.com/ec2/v2/home?region=us-east-1#Instances:sort=instanceId) and 3) my logged-in page for the site i really want to use your app for (https://learn.franklinlearningcenters.com/learning/dashboard).
i can view page source in notepad++ correctly from google page. when i rt-click on your app on the other two pages, nothing happens. notepad++ doesn't open. i can switch to any of the three pages and the action stays the same: google opens notepad++ reliably, the other two pages do nothing.
i tried the same test on chrome and the result is the same. i no longer get the view-source of an error page, i just get nothing.
note that all three sites will open notepad++ with view-source html BEFORE i login to the sites. it's only after i login that your app stops working.
hope this helps.

**Comment by asamuzaK** [comment]
2nd try build [5.1.0a4](https://github.com/asamuzaK/withExEditor/tree/master/dest "withExEditor/dest at master · asamuzaK/withExEditor")

**Comment by ghost** [comment]
no change of behavior in the three sites above with 5.1.0a4. 
just happened to reboot my machine before testing for whatever that's worth.
sorry...

**Comment by asamuzaK** [comment]
Really?
I tested 2nd case and got expected source of it.
Please open web console (Ctrl + Shift + K) / browser console (Ctrl + Shift + J) and see if there is any error logged.

**Comment by ghost** [comment]
ok, i got different behavior from firefox tonight, i don't know why. the only difference is that i had the two console windows open. tonight notepad++ did open with html code in it. 
the code was not the full html code of the page, but it was the same code as i get from a 'view page source' command. all the 'secure' html was missing in both cases, such as instance names, ids, ips, etc. 
however, for the site i really need this for, i still got no response from your app in firefox, even with the two consoles open and after clearing cookies/history. notepad++ did not open. no errors in the consoles. in fact not much data at all in the consoles.
attached are the console data and the html output.
[firefox-consoles.txt](https://github.com/asamuzaK/withExEditor/files/2052832/firefox-consoles.txt)


[home.txt](https://github.com/asamuzaK/withExEditor/files/2052834/home.txt)

**Comment by asamuzaK** [comment]
Debug build [withExEditor/dest at master · asamuzaK/withExEditor](https://github.com/asamuzaK/withExEditor/tree/master/dest "withExEditor/dest at master · asamuzaK/withExEditor")

Let's take a closer look at what is going on.

In this build, various values are output for debugging.
Go to [https://learn.franklinlearningcenters.com/learning/dashboard](https://learn.franklinlearningcenters.com/learning/dashboard "https://learn.franklinlearningcenters.com/learning/dashboard")
Open the web console (Ctrl + Shift + K) and then display the source of the page.
Then select all logs of the console, copy it, and send it to me.

**Comment by asamuzaK** [comment]
I reproduced the case on the editing page of Word Press, and could finally find out the cause.

I think that the source will be displayed as expected now with the latest build (v5.1.0a8).
Please try.

**Comment by asamuzaK** [comment]
@elrod-johnson 
Is your 3rd case still not working?

**Comment by ghost** [comment]
sorry, i've been out of the office for the past few days. 
i just installed 5.1.0a10 and tried case 3, but no good. notepad++ doesn't open. 
if you'll send an email from asamuzak.jp to e....@....., i'll send you login creds so you can test the site yourself. the account has minimal permissions, but i logged in as the account and tried to run your app and nothing happened. 
a regular view source command returns the expected html.
i appreciate all the time you're giving this. i really would like it to work. i'm manually copying and pasting the source code into notepad++ at least a dozen times a day.

**Comment by asamuzaK** [comment]
No, I don't think I should do that.
Sorry I could not be a help.

Note: removed your email address from previous comment.

**Comment by asamuzaK** [comment]
Few more things.
* Make sure that you are not blocking cookies and site data
  Check `about:preferences#privacy`
* If you are using proxy, what happens if you temporary disables it?
