### ISSUE TITLE
Shortcut to start the editor immediately

### ISSUE THREAD

**Issue by wavexx** [asamuzaK/withExEditor#9]
It would be nice to have a shortcut that I can press directly in editable fields to start the external editor without going through the context menu or toolbar button.

**Comment by asamuzaK** [comment]
Shift+F10 -> E (access key which you set)
It requires 2 actions, but is it so uncomfortable?

**Comment by wavexx** [comment]
On Sun, Jul 31 2016, asamuzaK (Kazz) notifications@github.com wrote:

> Shift+F10 -> E (access key which you set)
> It requires 2 actions, but is it so uncomfortable?

Yes :)

I've been using pentadactyl/itsalltext in the past, where you can start
the editor with one keystroke. If you do it often, it makes a lot of
sense.

**Comment by asamuzaK** [comment]
Released v1.7.0-a1 for test. [withExEditor :: Versions :: Add-ons for Firefox](https://addons.mozilla.org/en-US/firefox/addon/withexeditor/versions/beta)
Shortcut key is `Ctrl + Shift + key`

**Comment by asamuzaK** [comment]
Is this working as expected?
If so, I'll ship v1.7.0

**Comment by asamuzaK** [comment]
Released v1.7.0 [withExEditor :: Add-ons for Firefox](https://addons.mozilla.org/ja/firefox/addon/withexeditor/)

**Comment by wavexx** [comment]
On Wed, Aug 17 2016, "asamuzaK (Kazz)" notifications@github.com wrote:

> Is this working as expected?
> If so, I'll ship v1.7.0

Yes, it is. Thanks again for implementing it!

**Comment by braham-snyder** [comment]
@asamuzaK just a heads-up that I'm seeing this help-text on the options page, when I press the `Details` button:

> To execute the editor without going through the context menu, press 'Ctrl + Shift + key' ('Cmd + Shift + key' on Mac).

but I'm on OS X (El Capitan, FWIW), Firefox 53.0.2, and Ctrl + Shift + key is the shortcut that works for me--Cmd + Shift + key doesn't appear to do anything.

**Comment by asamuzaK** [comment]
Thanks, it's already fixed in v3 [withExEditor/options.html at master · asamuzaK/withExEditor](https://github.com/asamuzaK/withExEditor/blob/master/src/options/options.html#L241 "withExEditor/options.html at master · asamuzaK/withExEditor")

**Comment by asamuzaK** [comment]
withExEditor v3.0.6 released.
https://addons.mozilla.org/en-US/firefox/addon/withexeditor/

Don't forget to update withExEditorHost too.
https://github.com/asamuzaK/withExEditorHost
