### ISSUE TITLE
Errors with chrome 69

### ISSUE THREAD

**Issue by rtoy** [asamuzaK/withExEditor#94]
Using withexeditor version 5.4.0 and withexeditorhost 4.0.5, I'm unable to edit any text box.  When I inspect  background.html for the extension, there are errors like this:

>Unchecked runtime.lastError while running contextMenus.create: Cannot create item with duplicate id modeViewSource
    at createMenuItem (chrome-extension://koghhpkkcndhhclklnnnhcpkkplfkgoi/mjs/background.js:402:36)
background.html:1 Unchecked runtime.lastError while running contextMenus.create: Cannot create item with duplicate id modeViewSelection
    at createMenuItem (chrome-extension://koghhpkkcndhhclklnnnhcpkkplfkgoi/mjs/background.js:402:36)
background.html:1 Unchecked runtime.lastError while running contextMenus.create: Cannot create item with duplicate id modeEditText
    at createMenuItem (chrome-extension://koghhpkkcndhhclklnnnhcpkkplfkgoi/mjs/background.js:402:36)

I think these errors prevent me from using withExEditor at all. :-(

**Comment by asamuzaK** [comment]
Tested with Chrome Canary, but can not reproduce.

What happens if you reload withExEditor?

1. Click toolbar button and open options page
2. Click `Reload` button in the options page

or 

1. Open `More Tools` -> `Extensions` of Chrome menu
2. Click `Details` of withExEditor
3. Click `Extensions options`
4. Click `Reload` button in the options page

**Comment by asamuzaK** [comment]
Anyway, it should not try to create a menu if there is already a menu with that ID, I'll check what scenario this can happen.

**Comment by rtoy** [comment]
Ah, interesting.  Using Chrome 70 works.  But Chrome 69 doesn't work at all.  Reloading withExEditor doesn't change anything.  I can edit this message using Chrome 70 and withExEditor.

But using chrome 70 on crbug.com/new doesn't really work, but perhaps that's a different bug.  When I try to edit the description box, it keeps bringing up this text box for editing.

**Comment by asamuzaK** [comment]
Added some fixes and uploaded a try build.

1. Download zipped package from [withExEditor/dest at master · asamuzaK/withExEditor](https://github.com/asamuzaK/withExEditor/tree/master/dest) and unzip somewhere
2. Open `More Tools` -> `Extensions`
3. Enable `Developer Mode`
4. Disable installed withExEditor 5.4.0
5. Click `Load unpacked` and select folder of unzipped package

**Comment by asamuzaK** [comment]
Forget to note.
You need to add ID of unpacked withExEditor in `withexeditorhost.json`, like:

```
  "allowed_origins": [
    "chrome-extension://[unpacked withExEditor ID]/",
    "chrome-extension://koghhpkkcndhhclklnnnhcpkkplfkgoi/"
  ],
```

`withexeditorhost.json` should be in
* Windows: `C:\Users\[UserName]\AppData\Roaming\withexeditorhost\config\chrome`
* Mac: `~/Library/Application Support/withexeditorhost/config/chrome`
* Linux: `~/.config/withexeditorhost/config/chrome`

**Comment by rtoy** [comment]
Loading the new extension produces a warning: Unrecognized manifest key 'applications'.  And the edit icon has an exclamation point on it.

I also forgot to mention that I also enabled "Notify Host Error" on the configuration page.

(The locations I have are somewhat different, but I updated the json file as suggested.  Reloading the unpacked extension still produces an error.

**Comment by asamuzaK** [comment]
Thank you for cooperating with the test.

> Unrecognized manifest key 'applications'

That key is needed for Gecko browsers.
Even if that error is logged, it's okay.

> I also forgot to mention that I also enabled "Notify Host Error" on the configuration page.

What error notified?

**Comment by asamuzaK** [comment]
I've downloaded Chrome 69 (Win 10) and tested unpacked try build.
It seems working...

**Comment by rtoy** [comment]
Hmm. I'm running Linux.  Maybe my install of the host is messed up. (I installed the host manually from sources from github.)

I just enabled "Notify Host Error" to see if there were any errors happening.  I couldn't really tell if that did anything.  

I'll try to do a clean install now and see what happens. I just checked out v4.0.5, and did npm run setup and answered all the questions.

**Comment by asamuzaK** [comment]
Still in trouble?

**Comment by rtoy** [comment]
Yeah, still happens, but haven't had time to look into on my side.  Also happens on MacOS.  I rarely run this on Windows, so I haven't tested there yet.

**Comment by rtoy** [comment]
I updated to 5.4.2 and the latest withexeditorhost.  Everything seems to be working just fine now.  One other difference is I'm using Chrome 70 (beta) now.  Not sure which fixed the issue, but I am satisfied that everything is working fine now.

**Comment by asamuzaK** [comment]
I'll close this.

**Comment by rtoy** [comment]
Thanks for the fantastic tool.  It was pretty difficult these last few days when I was unable to use it.
